/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItemForm.java
 *
 * Created on Apr 3, 2012, 12:40:11 PM
 */
package com.assign2.view;

import com.assign2.Utils;
import com.assign2.business.Item;
import com.assign2.data.ItemAccess;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Jason Recillo
 */
public class ItemForm extends javax.swing.JPanel {
    /** Creates new form ItemForm */
    public ItemForm() {
        initComponents();
    }
    
    public ItemForm(Item i){
        try {
            initComponents();
            lblItemId.setText(String.valueOf(i.getItemId()));
            txtName.setText(i.getName());
            //category combo box
            txtPrice.setText(String.valueOf(i.getPrice()));
            txtDescription.setText(i.getDescription());
            imgItemImage.setIcon(new ImageIcon(ItemAccess.getItemImage(i.getItemId(), true)));
            spnQuantityInStock.setValue(i.getQtyInStock());
        } catch (SQLException ex) {
            Utils.log_error(ex.getMessage());
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblItemIdLabel = new javax.swing.JLabel();
        lblNameLabel = new javax.swing.JLabel();
        lblCategoryLabel = new javax.swing.JLabel();
        lblPriceLabel = new javax.swing.JLabel();
        lblDescriptionLabel = new javax.swing.JLabel();
        lblQuantityLabel = new javax.swing.JLabel();
        imgItemImage = new javax.swing.JLabel();
        lblItemId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cboCategories = new javax.swing.JComboBox();
        txtPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        spnQuantityInStock = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();

        lblItemIdLabel.setText("Item ID:");

        lblNameLabel.setText("Name:");

        lblCategoryLabel.setText("Category:");

        lblPriceLabel.setText("Price:");

        lblDescriptionLabel.setText("Description:");

        lblQuantityLabel.setText("Quantity in Stock:");

        imgItemImage.setMaximumSize(new java.awt.Dimension(100, 100));
        imgItemImage.setMinimumSize(new java.awt.Dimension(100, 100));
        imgItemImage.setPreferredSize(new java.awt.Dimension(100, 100));

        lblItemId.setText("ItemID");

        txtName.setText("Item Name");

        cboCategories.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtPrice.setText("Price");

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtDescription.setRows(5);
        txtDescription.setText("Description");
        txtDescription.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescription);

        btnSave.setText("Save");
        jPanel1.add(btnSave);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemIdLabel)
                            .addComponent(lblNameLabel)
                            .addComponent(lblCategoryLabel)
                            .addComponent(lblPriceLabel)
                            .addComponent(lblDescriptionLabel)
                            .addComponent(lblQuantityLabel))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemId)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboCategories, javax.swing.GroupLayout.Alignment.LEADING, 0, 84, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(spnQuantityInStock, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemIdLabel)
                            .addComponent(lblItemId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPriceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescriptionLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imgItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnQuantityInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cboCategories;
    private javax.swing.JLabel imgItemImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoryLabel;
    private javax.swing.JLabel lblDescriptionLabel;
    private javax.swing.JLabel lblItemId;
    private javax.swing.JLabel lblItemIdLabel;
    private javax.swing.JLabel lblNameLabel;
    private javax.swing.JLabel lblPriceLabel;
    private javax.swing.JLabel lblQuantityLabel;
    private javax.swing.JSpinner spnQuantityInStock;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
