/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItemForm.java
 *
 * Created on Apr 3, 2012, 12:40:11 PM
 */
package com.assign2.view;

import com.assign2.Utils;
import com.assign2.business.Item;
import com.assign2.data.ItemAccess;
import java.io.File;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Jason Recillo
 */
public class ItemForm extends javax.swing.JPanel {
    private File image;

    /** Creates new form ItemForm */
    public ItemForm() {
        initComponents();
    }

    public ItemForm(Item i) {
        try {
            initComponents();
            lblItemId.setText(String.valueOf(i.getItemId()));
            txtName.setText(i.getName());
            //category combo box
            txtPrice.setText(String.valueOf(i.getPrice()));
            txtDescription.setText(i.getDescription());
            imgItemImage.setIcon(new ImageIcon(ItemAccess.getItemImage(i.getItemId(), true)));
            spnQuantityInStock.setValue(i.getQtyInStock());
        } catch (SQLException ex) {
            Utils.log_error(ex.getMessage());
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblItemIdLabel = new javax.swing.JLabel();
        lblNameLabel = new javax.swing.JLabel();
        lblCategoryLabel = new javax.swing.JLabel();
        lblPriceLabel = new javax.swing.JLabel();
        lblDescriptionLabel = new javax.swing.JLabel();
        lblQuantityLabel = new javax.swing.JLabel();
        imgItemImage = new javax.swing.JLabel();
        lblItemId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cboCategories = new javax.swing.JComboBox();
        txtPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        spnQuantityInStock = new javax.swing.JSpinner();
        lblChangeImageLabel = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnChooseImage = new javax.swing.JButton();
        lblImagePath = new javax.swing.JLabel();

        lblItemIdLabel.setText("Item ID:");

        lblNameLabel.setText("Name:");

        lblCategoryLabel.setText("Category:");

        lblPriceLabel.setText("Price:");

        lblDescriptionLabel.setText("Description:");

        lblQuantityLabel.setText("Quantity in Stock:");

        imgItemImage.setMaximumSize(new java.awt.Dimension(100, 100));
        imgItemImage.setMinimumSize(new java.awt.Dimension(100, 100));
        imgItemImage.setPreferredSize(new java.awt.Dimension(100, 100));

        lblItemId.setText("ItemID");

        txtName.setText("Item Name");

        txtPrice.setText("Price");

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtDescription.setRows(5);
        txtDescription.setText("Description");
        txtDescription.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescription);

        lblChangeImageLabel.setText("Image:");

        btnSave.setText("Save");

        btnCancel.setText("Cancel");

        btnChooseImage.setText("Choose File...");
        btnChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseImageActionPerformed(evt);
            }
        });

        lblImagePath.setText("placeholder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imgItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemIdLabel)
                            .addComponent(lblNameLabel)
                            .addComponent(lblCategoryLabel)
                            .addComponent(lblPriceLabel)
                            .addComponent(lblDescriptionLabel)
                            .addComponent(lblQuantityLabel)
                            .addComponent(lblChangeImageLabel))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemId)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(spnQuantityInStock, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboCategories, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnChooseImage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImagePath, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemIdLabel)
                            .addComponent(lblItemId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPriceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescriptionLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnQuantityInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantityLabel)))
                    .addComponent(imgItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChangeImageLabel)
                    .addComponent(btnChooseImage)
                    .addComponent(lblImagePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseImageActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            image = fc.getSelectedFile();
            String path = image.getAbsolutePath();
            lblImagePath.setText(String.format("%s...%s", path.substring(0, 9), path.substring(path.length() - 10, path.length() - 1)));
        }
    }//GEN-LAST:event_btnChooseImageActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChooseImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cboCategories;
    private javax.swing.JLabel imgItemImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoryLabel;
    private javax.swing.JLabel lblChangeImageLabel;
    private javax.swing.JLabel lblDescriptionLabel;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JLabel lblItemId;
    private javax.swing.JLabel lblItemIdLabel;
    private javax.swing.JLabel lblNameLabel;
    private javax.swing.JLabel lblPriceLabel;
    private javax.swing.JLabel lblQuantityLabel;
    private javax.swing.JSpinner spnQuantityInStock;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
